packages:
  - apps/*
  - packages/*
allowBuilds:
  '@google/genai': false
  koffi: false
  msw: false
  protobufjs: false

catalog:
  "@types/bun": "latest"
  "typescript": "~5.9.3"

onlyBuiltDependencies:
  - msw
