import { useCallback, useState, useEffect, useRef } from 'react';
import type { AIReviewItem, ChangeGroup } from '@/types';
import { generateGrouping, generateAIReview } from '@/lib/api';
import { transformAIReviewItems, transformChangeGroups } from '@/lib/transforms';

interface UseAIReviewOptions {
  autoGenerate?: boolean;
}

interface UseAIReviewReturn {
  items: AIReviewItem[];
  groups: ChangeGroup[];
  summary: string;
  triggerReview: () => Promise<void>;
  generateGroups: () => Promise<void>;
  isLoading: boolean;
  isGeneratingGroups: boolean;
  error: Error | null;
}

export function useAIReview(options: UseAIReviewOptions = {}): UseAIReviewReturn {
  const { autoGenerate = true } = options;
  const [items, setItems] = useState<AIReviewItem[]>([]);
  const [summary, setSummary] = useState<string>('');
  const [groups, setGroups] = useState<ChangeGroup[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isGeneratingGroups, setIsGeneratingGroups] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  
  const hasAutoGenerated = useRef(false);

  const triggerReview = useCallback(async () => {
    setIsLoading(true);
    setError(null);

    try {
      const response = await generateAIReview();
      setItems(transformAIReviewItems(response.items));
      setSummary(response.summary);
    } catch (err) {
      console.error('Failed to generate AI review:', err);
      setError(err instanceof Error ? err : new Error('Failed to generate AI review'));
    } finally {
      setIsLoading(false);
    }
  }, []);

  const generateGroups = useCallback(async () => {
    setIsGeneratingGroups(true);
    setError(null);

    try {
      const serverGroups = await generateGrouping();
      setGroups(transformChangeGroups(serverGroups));
    } catch (err) {
      console.error('Failed to generate groups:', err);
      setError(err instanceof Error ? err : new Error('Failed to generate groups'));
    } finally {
      setIsGeneratingGroups(false);
    }
  }, []);

  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated.current && groups.length === 0) {
      hasAutoGenerated.current = true;
      generateGroups();
    }
  }, [autoGenerate, generateGroups, groups.length]);

  return {
    items,
    groups,
    summary,
    triggerReview,
    generateGroups,
    isLoading,
    isGeneratingGroups,
    error,
  };
}
