import { useCallback, useState, useEffect, useRef } from 'react';
import type { AIReviewItem, ChangeGroup } from '@/types';
import { generateGrouping, generateAIReview } from '@/lib/api';

interface UseAIReviewOptions {
  prNumber?: number;
  repo?: string;
  autoGenerate?: boolean;
}

interface UseAIReviewReturn {
  items: AIReviewItem[];
  groups: ChangeGroup[];
  summary: string;
  triggerReview: () => Promise<void>;
  generateGroups: () => Promise<void>;
  isLoading: boolean;
  isGeneratingGroups: boolean;
  error: Error | null;
}

export function useAIReview(options: UseAIReviewOptions = {}): UseAIReviewReturn {
  const { prNumber, repo, autoGenerate = true } = options;
  const [items, setItems] = useState<AIReviewItem[]>([]);
  const [summary, setSummary] = useState<string>('');
  const [groups, setGroups] = useState<ChangeGroup[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isGeneratingGroups, setIsGeneratingGroups] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  
  // Track if auto-generation has been triggered to prevent multiple calls
  const hasAutoGenerated = useRef(false);

  const triggerReview = useCallback(async () => {
    if (!prNumber) {
      console.warn('Cannot trigger review: PR number is required');
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const response = await generateAIReview(prNumber, repo);
      
      // Transform server items to client AIReviewItem type
      const clientItems: AIReviewItem[] = response.items.map((item) => ({
        id: item.id,
        filePath: item.filePath,
        lineNumber: item.lineNumber,
        severity: item.severity,
        message: item.message,
        suggestion: item.suggestion,
      }));

      setItems(clientItems);
      setSummary(response.summary);
    } catch (err) {
      console.error('Failed to generate AI review:', err);
      setError(err instanceof Error ? err : new Error('Failed to generate AI review'));
    } finally {
      setIsLoading(false);
    }
  }, [prNumber, repo]);

  const generateGroups = useCallback(async () => {
    if (!prNumber) {
      console.warn('Cannot generate groups: PR number is required');
      return;
    }

    setIsGeneratingGroups(true);
    setError(null);

    try {
      const serverGroups = await generateGrouping(prNumber, repo);
      
      // Transform server groups to client ChangeGroup type
      const clientGroups: ChangeGroup[] = serverGroups.map((group) => ({
        id: group.id,
        title: group.title,
        summary: group.summary,
        files: group.files,
        totalAdditions: group.totalAdditions,
        totalDeletions: group.totalDeletions,
      }));

      setGroups(clientGroups);
    } catch (err) {
      console.error('Failed to generate groups:', err);
      setError(err instanceof Error ? err : new Error('Failed to generate groups'));
    } finally {
      setIsGeneratingGroups(false);
    }
  }, [prNumber, repo]);

  // Auto-generate groups on mount when PR number is available
  useEffect(() => {
    if (prNumber && autoGenerate && !hasAutoGenerated.current && groups.length === 0) {
      hasAutoGenerated.current = true;
      generateGroups();
    }
  }, [prNumber, autoGenerate, generateGroups, groups.length]);

  // Reset auto-generation flag when PR number changes
  useEffect(() => {
    hasAutoGenerated.current = false;
    setGroups([]);
    setItems([]);
    setSummary('');
    setError(null);
  }, [prNumber]);

  return {
    items,
    groups,
    summary,
    triggerReview,
    generateGroups,
    isLoading,
    isGeneratingGroups,
    error,
  };
}
