import { useCallback, useState, useEffect, useRef } from 'react';
import type { RelatedFile } from '@/types';
import { findRelatedFiles } from '@/api/ai';

interface UseRelatedFilesOptions {
  autoGenerate?: boolean;
}

interface UseRelatedFilesReturn {
  files: RelatedFile[];
  findFiles: (additionalContext?: string) => Promise<boolean>;
  isLoading: boolean;
  error: Error | null;
}

export function useRelatedFiles(options: UseRelatedFilesOptions = {}): UseRelatedFilesReturn {
  const { autoGenerate = false } = options;
  const [files, setFiles] = useState<RelatedFile[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  
  const hasAutoGenerated = useRef(false);

  const findFiles = useCallback(async (additionalContext?: string): Promise<boolean> => {
    setIsLoading(true);
    setError(null);

    try {
      const serverFiles = await findRelatedFiles(additionalContext);
      setFiles(serverFiles);
      return true;
    } catch (err) {
      console.error('Failed to find related files:', err);
      setError(err instanceof Error ? err : new Error('Failed to find related files'));
      return false;
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated.current && files.length === 0) {
      hasAutoGenerated.current = true;
      findFiles();
    }
  }, [autoGenerate, findFiles, files.length]);

  return {
    files,
    findFiles,
    isLoading,
    error,
  };
}
