import { useCallback, useState, useEffect, useRef } from 'react';
import type { RelatedFile } from '@/types';
import { findRelatedFiles } from '@/lib/api';

interface UseRelatedFilesOptions {
  prNumber?: number;
  repo?: string;
  autoGenerate?: boolean;
}

interface UseRelatedFilesReturn {
  files: RelatedFile[];
  findFiles: () => Promise<void>;
  isLoading: boolean;
  error: Error | null;
}

export function useRelatedFiles(options: UseRelatedFilesOptions = {}): UseRelatedFilesReturn {
  const { prNumber, repo, autoGenerate = false } = options;
  const [files, setFiles] = useState<RelatedFile[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  
  const hasAutoGenerated = useRef(false);

  const findFiles = useCallback(async () => {
    if (!prNumber) {
      console.warn('Cannot find related files: PR number is required');
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const serverFiles = await findRelatedFiles(prNumber, repo);
      setFiles(serverFiles);
    } catch (err) {
      console.error('Failed to find related files:', err);
      setError(err instanceof Error ? err : new Error('Failed to find related files'));
    } finally {
      setIsLoading(false);
    }
  }, [prNumber, repo]);

  useEffect(() => {
    if (prNumber && autoGenerate && !hasAutoGenerated.current && files.length === 0) {
      hasAutoGenerated.current = true;
      findFiles();
    }
  }, [prNumber, autoGenerate, findFiles, files.length]);

  useEffect(() => {
    hasAutoGenerated.current = false;
    setFiles([]);
    setError(null);
  }, [prNumber]);

  return {
    files,
    findFiles,
    isLoading,
    error,
  };
}
