import { useCallback, useState, useEffect, useRef } from 'react';
import type { AIReviewItem, ChangeGroup, AIReviewCategory, AIReviewRunMode } from '@/types';
import { generateGrouping, generateAIReview } from '@/api/ai';
import { transformAIReviewItems, transformChangeGroups } from '@/lib/transforms';

export interface TriggerReviewOptions {
  reviewCategories?: AIReviewCategory[];
  runMode?: AIReviewRunMode;
}

interface UseAIReviewOptions {
  autoGenerate?: boolean;
}

interface UseAIReviewReturn {
  items: AIReviewItem[];
  groups: ChangeGroup[];
  summary: string;
  triggerReview: (additionalContext?: string, options?: TriggerReviewOptions) => Promise<boolean>;
  generateGroups: (additionalContext?: string) => Promise<boolean>;
  isLoading: boolean;
  isGeneratingGroups: boolean;
  error: Error | null;
}

export function useAIReview(options: UseAIReviewOptions = {}): UseAIReviewReturn {
  const { autoGenerate = true } = options;
  const [items, setItems] = useState<AIReviewItem[]>([]);
  const [summary, setSummary] = useState<string>('');
  const [groups, setGroups] = useState<ChangeGroup[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isGeneratingGroups, setIsGeneratingGroups] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  
  const hasAutoGenerated = useRef(false);

  const triggerReview = useCallback(async (additionalContext?: string, options?: TriggerReviewOptions): Promise<boolean> => {
    setIsLoading(true);
    setError(null);

    try {
      const response = await generateAIReview({
        additionalContext,
        reviewCategories: options?.reviewCategories,
        runMode: options?.runMode,
      });
      setItems(transformAIReviewItems(response.items));
      setSummary(response.summary);
      return true;
    } catch (err) {
      console.error('Failed to generate AI review:', err);
      setError(err instanceof Error ? err : new Error('Failed to generate AI review'));
      return false;
    } finally {
      setIsLoading(false);
    }
  }, []);

  const generateGroups = useCallback(async (additionalContext?: string): Promise<boolean> => {
    setIsGeneratingGroups(true);
    setError(null);

    try {
      const serverGroups = await generateGrouping(additionalContext);
      setGroups(transformChangeGroups(serverGroups));
      return true;
    } catch (err) {
      console.error('Failed to generate groups:', err);
      setError(err instanceof Error ? err : new Error('Failed to generate groups'));
      return false;
    } finally {
      setIsGeneratingGroups(false);
    }
  }, []);

  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated.current && groups.length === 0) {
      hasAutoGenerated.current = true;
      generateGroups();
    }
  }, [autoGenerate, generateGroups, groups.length]);

  return {
    items,
    groups,
    summary,
    triggerReview,
    generateGroups,
    isLoading,
    isGeneratingGroups,
    error,
  };
}
